### ISSUE TITLE
font-smooth のスタイルをガイドラインに追加する

### ISSUE THREAD

**Issue by ktsn** [oRoFE/oRoFE.github.io#50]
font-smooth 系のスタイル、結構デザイナーからの要望で上がってくるので、ガイドラインに入れても良い気がしてきました。いかがでしょうか？

```css
body {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  font-smooth: always;
}
```

ブラウザごとで書き方が異なってたり、指定される書き方が間違ってたりもするので、正しい記述を保証する意味でもあると良いのではないかと思います。
