### ISSUE TITLE
リセットスタイル変更： box-sizing

### ISSUE THREAD

**Issue by koya-iwasaki** [oRoFE/oRoFE.github.io#51]
デフォルトで `box-sizing: border-box` にしちゃってもいいかもしれません。
IE8以上対応なので、ガイドラインの対象ブラウザを満たします。
必要なところだけ `box-sizing: content-box` にする。
```css
* {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
```
