### ISSUE TITLE
リセットスタイルの box-sizing を擬似要素にも適用する

### ISSUE THREAD

**Issue by ktsn** [oRoFE/oRoFE.github.io#72]
ref #51

`*` だけだと擬似要素に適用されないようです。

```css
*,
*::before,
*::after {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}
```
