### ISSUE TITLE
button 系のリセットスタイルに margin: 0; と border: none; を追加する

### ISSUE THREAD

**Issue by ktsn** [oRoFE/oRoFE.github.io#83]
ブラウザによってたまに margin が入ってずれたりするので追加したいです。
また、業務ではほぼブラウザデフォルトのスタイルは使わないと思います。

``` css
button,
input[type="button"],
input[type="submit"] {
  mergin: 0;
  border: none;
  // padding: 0; も入れるべき？
}
```
